### ISSUE TITLE
dateutils fails to build on centos 6

### ISSUE THREAD

**Issue by pdvnl** [hroptatyr/dateutils#104]
dateutils installed fine on mac osx and fedora 30. now trying centos 6.

in INSTALL is stated that you need as compiler gcc >= 4.6.0 which is not available in centos 6.
cern software collection devtoolset-2 provides gcc 4.8.2.

this produces the following error:
```
  GEN    version.mk
make[1]: Entering directory `/data/develop/dateutils/dateutils/build-aux'
make  all-am
make[2]: Entering directory `/data/develop/dateutils/dateutils/build-aux'
  CC     yuck-yuck-scmver.o
/tmp/ccMmUULw.s: Assembler messages:
/tmp/ccMmUULw.s:235: Error: expecting string instruction after `rep'
make[2]: *** [yuck-yuck-scmver.o] Error 1
make[2]: Leaving directory `/data/develop/dateutils/dateutils/build-aux'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/data/develop/dateutils/dateutils/build-aux'
/bin/sh: line 3: yuck: command not found
Making all in build-aux
make[1]: Entering directory `/data/develop/dateutils/dateutils/build-aux'
make  all-am
make[2]: Entering directory `/data/develop/dateutils/dateutils/build-aux'
  CC     yuck-yuck-scmver.o
/tmp/ccWf9PvR.s: Assembler messages:
/tmp/ccWf9PvR.s:235: Error: expecting string instruction after `rep'
make[2]: *** [yuck-yuck-scmver.o] Error 1
make[2]: Leaving directory `/data/develop/dateutils/dateutils/build-aux'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/data/develop/dateutils/dateutils/build-aux'
make: *** [all-recursive] Error 1
```

**Comment by hroptatyr** [comment]
Hello,
thanks for the report.  However, I don't quite understand how I can be useful in this regard.  I can assure you that dateutils (and code in `build-aux/`) is 100% assembler-free.

The erroneous line seems to be the result of a C compiler emitting code that isn't suitable for the target platform's assembler.  By any chance, did you attempt a cross-compile?  Can you re-run make with `V=1` so I can see the invoked compiler, assembler and linker command lines?

**Comment by hroptatyr** [comment]
It's `make V=1`  (with a capital-V).

**Comment by pdvnl** [comment]
i'm sorry about 'v' versus 'V'.

today I tried devtoolset-7 on centos 6 and it compiles (with lots of warnings).

in summary:
```
CENTOS-6
gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23) -> compilations fails

scl enable devtoolset-2 'gcc --version'
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15) -> compilation fails

scl enable devtoolset-7 'gcc --version'
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5) -> OK

CENTOS-7
gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39) -> OK

FEDORA-30
gcc --version
gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1) -> OK

MAC OS-X (MacPorts)
gcc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1) -> OK
```

i guess the compiler version is an issue. what are you using?

**Comment by hroptatyr** [comment]
Development is taking place with Intel's icc, 2019.5 at the moment.  But before releases I use various compilers and systems, among them a gcc 4.8.5.

**Comment by mattdm** [comment]
CentOS 6 EOL was November, 2020, one year ago. I'd suggest closing this.

**Comment by hroptatyr** [comment]
Thanks for the reminder.
