### ISSUE TITLE
dateutils 0.4.8 release missing artifacts

### ISSUE THREAD

**Issue by grazzolini** [hroptatyr/dateutils#122]
Hi,

The 0.4.8 release is missing the download artifacts like the signature and the tar file. Also, it is just a tag, not a proper release. Thanks in advance.

**Comment by hroptatyr** [comment]
Yes, travis deployment is broken. :(

**Comment by jubalh** [comment]
Also have been waiting for this since an hour hehe :)

**Comment by hroptatyr** [comment]
Hang on, I'll do it manually.

**Comment by hroptatyr** [comment]
should be rectified now .oO(hopefully)

**Comment by jubalh** [comment]
Yep! Thank you.

**Comment by grazzolini** [comment]
Thanks, I have updated the package on Arch Linux as well.
