### ISSUE TITLE
When using the format "%s%N", ddiff: Error: reference DATE must be specified

### ISSUE THREAD

**Issue by ouuan** [hroptatyr/dateutils#123]
When running `datediff -i "%s%N" 1100000000000000000 1000000000000000000`, I got the error: `ddiff: Error: reference DATE must be specified`.

This happens since bd914dffe706d321a48e8dc886306c26f7284381. Before that commit, the output is `-100000000s`.

**Comment by hroptatyr** [comment]
Hey Yufan, thanks for the report.  I didn't even know that was possible.

I submitted a quick fix in a97581212.
