### ISSUE TITLE
Some odd dateadd operation results

### ISSUE THREAD

**Issue by Sadi58** [hroptatyr/dateutils#125]
I tried using **dateutils** to **shift exif dates and times** in image and video files in the hope that I could get more precise results than **exiftool**, but unfortunately I've got worse results - under Kubuntu 20.10 (dateutils version 0.4.5-1.1).

Here are two examples:
1. Shifting "2021:01:01 12:12:12" "1:1:1 10:10:10" forward, which is a simple operation:
exiftool => ` ... -GlobalTimeShift "+01:01:01 10:10:10" ...` => 2022:02:02 22:22:22 (correct)
dateutils => `... 2021-01-01T12:12:12 +1y1m1d10h10m10s` => 2022-**01**-02T22:**23**:22 (wrong month and minute)
2. Shifting "2022:02:02 22:22:22" "01:11:01 02:38:39" forward, which is more complicated:
exiftool => `... -GlobalTimeShift "+01:11:01 02:38:39" ...` => 2024:01:**07** 01:01:01 (wrong day, should be **04**)
dateutils => `... 2022-02-02T22:22:22 +1y11m1d2h38m39s` => **2023**-**02**-04T01:**12**:01 (wrong year, month and minute)

**Comment by hroptatyr** [comment]
The suffix for adding months is `mo` not `m`.  The latter is the suffix for minutes.

**Comment by Sadi58** [comment]
Ooops, I should have suspected that month and minute should be abridged differently, sorry.
It's percetly working now, thanks!
