### ISSUE TITLE
`dateconv … now` does not observe time zone

### ISSUE THREAD

**Issue by noyannus** [hroptatyr/dateutils#126]
`dateconv … now` does not observe time zone. Compared with `date`:

![dateconv](https://user-images.githubusercontent.com/6339921/119116383-79366c00-ba28-11eb-8246-256207bbe2bb.png)

**Comment by hroptatyr** [comment]
Hi, thanks for the report. That's deliberate.  Tools from the dateutils suite do not interact with the environment.  Time zones have to be specified explicitly:

    $ dateconv -z Africa/Johannesburg -f "%a, %F %T %Z" now

**Comment by noyannus** [comment]
Thanks for taking the time to explain!
