### ISSUE TITLE
dadd segaults on MacOSX

### ISSUE THREAD

**Issue by rudimeier** [hroptatyr/dateutils#13]
I see many segfaults when running the test suite (not only dadd). Seems option --zone is always involved.

<pre>
localhost:dateutils-0.2.4-26-gd50dd27c svp$ gdb src/dadd
GNU gdb 6.3.50-20050815 (Apple version gdb-1515) (Sat Jan 15 08:33:48 UTC 2011)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin"...Reading symbols for shared libraries .. done

(gdb) run  +1d23h -z Europe/Berlin
Starting program: /Users/svp/tmpsrc/dateutils-0.2.4-26-gd50dd27c/src/dadd +1d23h -z Europe/Berlin
Reading symbols for shared libraries +. done

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000100068000
0x00000001000049c3 in __conv_zif [inlined] () at /Users/svp/tmpsrc/dateutils-0.2.4-26-gd50dd27c/lib/tzraw.c:207
207                     tgt->trs[i].tr = be32toh(src->trs[i].tr);
(gdb) bt
#0  0x00000001000049c3 in __conv_zif [inlined] () at /Users/svp/tmpsrc/dateutils-0.2.4-26-gd50dd27c/lib/tzraw.c:207
#1  0x00000001000049c3 in __copy_conv [inlined] () at /Users/svp/tmpsrc/dateutils-0.2.4-26-gd50dd27c/lib/tzraw.c:258
#2  0x00000001000049c3 in zif_open (file=<value temporarily unavailable, due to optimizations>) at tzraw.c:331
#3  0x000000010001a9ac in main (argc=4, argv=<value temporarily unavailable, due to optimizations>) at dadd.c:277

</pre>

**Comment by hroptatyr** [comment]
Other reports indicate this works now.  Reopen if the error still persists.
