### ISSUE TITLE
dateconv -S -i '%b/%d %Y at %I:%M %P' hangs on ubuntu 20.04

### ISSUE THREAD

**Issue by derailius** [hroptatyr/dateutils#133]
when i try dateconv -S -i '%b/%d %Y at %I:%M %P' terminal just hangs. I used to be able to use this command though. am i doing something wrong?

**Comment by hroptatyr** [comment]
Hi,
it's waiting for input from stdin. Either present a date in that format on the line, or echo it to stdin.

    $ dateconv -S -i '%b/%d %Y at %I:%M %P' 'Mar/02 2022 at 4:00 pm'
    2022-03-02T16:00:00

or

    $ echo 'Mar/02 2022 at 4:00 pm' | dateconv -S -i '%b/%d %Y at %I:%M %P'
    2022-03-02T16:00:00

**Comment by derailius** [comment]
ooooops...lol thank you!
