### ISSUE TITLE
Starting with year and week number, how to have the date Monday

### ISSUE THREAD

**Issue by aborruso** [hroptatyr/dateutils#136]
I have in example year 2021 and week 32, is there a way to use dateutils to have the iso date of that week monday?

Thank you

**Comment by hroptatyr** [comment]
Hi, using the ISO notation:

    $ dateconv 2021-W32-1 -f %F
    2021-08-09

using format specifiers:

    $ dateconv -i '%Y %V %w' '2021 32 1' -f %F
    2021-08-09

Things change if your week counting is not ISO, there's support for the traditional week count with Monday based weeks (use `%W` instead of `%V`) but anything other than that is not supported.

**Comment by aborruso** [comment]
Really great, thank you
