### ISSUE TITLE
Skip weekends on dateadd and other commands

### ISSUE THREAD

**Issue by karthik** [hroptatyr/dateutils#145]
One usecase I have (and I suspect many others) is to add x business days to a particular date. So this would require skipping weekends.  Right now skip is only possible with `dateseq`

```
dateseq 2010-01-01 2010-01-10 --skip sat,sun
```

but this would also be very useful to have for `dateadd`, like so

```
 dateadd today +230d --skip sat,sun
```

**Comment by hroptatyr** [comment]
Hi,
you mean like this

    $ dateadd today +230b
    2023-05-12

**Comment by karthik** [comment]
Amazing! Thank you!
