### ISSUE TITLE
Please update config.guess file shipped with release tarball

### ISSUE THREAD

**Issue by xctan** [hroptatyr/dateutils#147]
Currently the config.guess file in the tarball is too old to properly detect RISC-V platform. It can be updated by executing `autoreconf -fiv`.

**Comment by hroptatyr** [comment]
Thanks for letting me know. I'm using Travis for artefact generation, and by default they're using Ubuntu Xenial (16.04).  In cc70bbfa3205375925dd6f7bab88cfdab1c99206 I upped the distro image which means the next release tarball should automatically contain the most recent config.guess script.
