### ISSUE TITLE
Rules differ

### ISSUE THREAD

**Issue by mountaineerbr** [hroptatyr/dateutils#153]
The following input:

```
1988-01-30T00:00:01 1989-03-01T23:01:58
```

(may be UTC...)

Gives different results from my script:

Yours give:

```
1Y 1M *9W* 0D 23h 1m 57s	
```

  (cmd: `datediff -f'%Y %m %w %d  %H %M %S'`)

While my [datediff.sh](https://github.com/mountaineerbr/shellDatediff) script correctly gives the answer:

```
1Y 0M 4W 2D 23h 1m 57s
```

In that Y stands for years, M for months, W for weeks, D for days, h for hours, m for minutes, and s for seconds.
 
Isn't something weyrd?

**Comment by hroptatyr** [comment]
Hi, thanks for the report. You're right, looks like a bug.

**Comment by mountaineerbr** [comment]
Hello, I found some more bugs related to C-code datediff in my testing logs.

Below are four errs. Results following sh means results from my datediff script and dd results are C-code datediff. Don't really know if these bugs are related to a single incomplete rule or more in C-code datediff.


```
1988-01-30T12:01:01+00:00 |  1989-03-02T00:58:58+00:00
sh=1Y 1M 0W 0D 12h 57m 57s
dd=1Y 1M 9W 0D 12h 57m 57s


1988-01-31T01:00:00+00:00 |  1989-03-01T23:01:58+00:00
sh=1Y 0M 4W 1D 22h 1m 58s
dd=1Y 1M 8W 6D 22h 1m 58s


1988-01-31T00:00:00+00:00 |  1989-03-01T00:00:01+00:00
sh=1Y 0M 4W 1D 0h 0m 1s
dd=1Y 1M 8W 6D 0h 0m 1s

1988-01-31T23:01:00+00:00 |  1988-03-01T23:58:00+00:00
sh=0Y 0M 4W 2D 0h 57m 0s
dd=0Y 1M 9W 0D 0h 57m 0s

```

I am not able to read C code well enough to understand all the component
systems nor follow the references.

May I ask if you wrote all the internal libs or have them imported from
some lower C libs? Thanks

**Comment by hroptatyr** [comment]
Hiya, they should all be fixed now.  Stupid mistake on my side.

**Comment by mountaineerbr** [comment]
OK, thanks anyways for never fully answering a question from myself about this weyrd calendrical calculations we have our paws on..

I admire anyone whoever has got mathematical skills, I have got none whatsoever but it was a good journey, anywho mate good bye I will cancel this issue, hopefully you guys have lots of people to talk about calendrical calculations in your nucleaus

**Comment by hroptatyr** [comment]
Oh what question was that then?  It was indeed me who wrote all the internals, dateutils does not depend on libc (well it does for I/O)
