### ISSUE TITLE
Question: Can datetest suport multiple conditions

### ISSUE THREAD

**Issue by mailsanchu** [hroptatyr/dateutils#157]
I want to test a given date between 2 dates. Currently, I am doing two conditions. Is it possible to combine the two if conditions?

```
	if datetest today --gt "$current" -i "$f"; then
		if datetest today --lt "$(dateadd "$current" +13d -i "$f" -f "$f")" -i "$f"; then
```

**Comment by hroptatyr** [comment]
Hi,
no you cannot have multiple conditions on one line but you can use the shell's conjunction operator to do away with a nested if:

    $ if datetest today --get "$current" -i "$f" && datetest today --lt "$(...)"; then
      ...
