### ISSUE TITLE
Accept offsets in --zone, -z flags

### ISSUE THREAD

**Issue by Earnestly** [hroptatyr/dateutils#159]
There isn't a single portable way to determine zone names such as `Europe/London` but it is possible to derive the offset via ` date +%z` such as `+0100`.

Would it be possible for the `--zone`, `-z` flags to accept these offsets instead of requiring zone names?

(Worth mentioning that `date +%Z` names, such as BST, aren't accepted by `--zone` which is a bit odd.)

**Comment by Earnestly** [comment]
No worries about delays, grateful to have dateutils at all.

I don't disagree that names should be available but my concern is that currently there's no way to determine them portably (the recent POSIX 8 issue doesn't touch it either). Instead there's several different approaches:

```sh
# systemd
timedatectl -P Timezone show
Europe/London

# /etc/localtime symlinks
readlink /etc/localtime
/usr/share/zoneinfo/Europe/London

# Or just parsing zone files, not shown here
```

The other trouble with offsets is that an offset might only be used briefly in countries with DST and I'm not sure can be expressed using just offsets when converting times or producing sequences.

Do you think it's reasonable for dateutils to provide a utility that can somewhat portably using the tz C API print the zone name instead?

**Comment by hroptatyr** [comment]
I might be wrong but didn't I implement `-z localtime` for you for this purpose?

You are correct about pure offsets (which btw can also be obtained using IANA's Etc/GMT-1, etc.), they're only good for countries with no DST switches.

> Do you think it's reasonable for dateutils to provide a utility that can somewhat portably using the tz C API print the zone name instead?

Which one?  POSIX has tzname(3) ... the string looks like PST8PDT or MET-1MEST, they come from inside the tzfile that is pointed to by /etc/localtime.  GNU libc might have GNU extensions (which aren't very portable).

And also systemd's timedated is simply using /etc/localtime (see https://cgit.freedesktop.org/systemd/systemd/tree/src/timedate/timedated.c l.71)

Btw `-z` accepts `localtime` already.

**Comment by Earnestly** [comment]
Oh, I think `localtime` would actually solve all my current use cases. I had also forgotten about this old comment: https://github.com/hroptatyr/dateutils/issues/97#issuecomment-1826380633

Thank you very much (perhaps it might be worth documenting `localtime` for `-z` flags?)
