### ISSUE TITLE
dateutils missing an option to use STDIN as one of the parameters

### ISSUE THREAD

**Issue by emk2203** [hroptatyr/dateutils#168]
Don't know if I overlooked it, but I tried with `-` and also looked in the man page to find a way to use STDIN as one parameter.

Would this be an option to implement? I know I can use a construct like `datediff $(...) now` instead, but it would be easier to maintain if pipes were possible.

**Comment by hroptatyr** [comment]
Hi there, thanks for your report.  I think you might want to try

    $ datediff now < FILE

e.g.

    $ datediff now <<EOF
    2024-11-19T10:00:00
    EOF

You will get negative durations for events in the past and positive durations for events in the future.

**Comment by emk2203** [comment]
Good suggestion, but I was looking for a use case where I extract the date from an existing file (log) and cannot use FILE directly.

I want to use the result of an `awk|cut|sed|whatever` operation as an input for datediff. Example: `head -n 1 /var/log/pacman.log | cut -c 2-11 | datediff - now` to find out how long since this system was set up. But this doesn't work since the dateutils don't accept input from STDIN. 

Would this be a possible new option/feature if it doesn't exist?

**Comment by hroptatyr** [comment]
Ok, got you.  Does

    $ head -n 1 /var/log/pacman.log | cut -c 2-11 | datediff now

not suit your needs?

**Comment by emk2203** [comment]
Embarrassing oversight on my side. I was fixated on having the dash somewhere in the command to use STDIN.

Issue closed, Solution: PEBKAC.
