### ISSUE TITLE
minor warning in dgrep man page

### ISSUE THREAD

**Issue by mattdm** [hroptatyr/dateutils#32]
Basically, this:

     $ man --warnings ./dgrep.man > /dev/null
     <standard input>:12: warning: macro `>',' not defined

This is ... not what I'd call high priority, but there it is. :)

**Comment by hroptatyr** [comment]
Hm, I can't reproduce this with 

    $ nroff -v
    GNU nroff (groff) version 1.22.2

and, as far as I understand, nroff macro names shouldn't start with `>` anyway.

**Comment by hroptatyr** [comment]
I've been told this has been fixed in 6eb13b50 (and another similar one in 377937d2).  Can you confirm?

**Comment by mattdm** [comment]
Confirmed fixed. Thanks!
