### ISSUE TITLE
Possible to change binary command prefix?

### ISSUE THREAD

**Issue by mattdm** [hroptatyr/dateutils#34]
So, this falls the intersection of "all the good names are taken" and "flat namespaces are kinda insane", but we realised that the `dtest` command conflicts with a command of the same name already in Red Hat Enterprise Linux for testing the "dapl" library from openfabrics. Now, arguably, it'd make a lot more sense for _that_ command to be named something less generic, but I don't know how much traction I'd get there. I can also ignore that and just package this for Fedora instead of for Fedora + EPEL, but that seems a little sad.

How do you feel about changing the `d` prefix of these commands to `date`, so `datetest`, `dateconv`, and etc., either just for Fedora/EPEL or as a universal "hey, we weren't 1.0 yet anyway" change? I appreciate the convenience of shorter names, but seems like putting "date" there would help with the current minor conflict _and_ avoid potential other conflicts with other utilities around any future thing which happens to start with d.

Not a huge deal but figured I'd check — thanks!

**Comment by hroptatyr** [comment]
Hm, I'm sort of used to this discussion, and I agree, something must be done.  However, I tend to go for something more nebulous for a prefix, like dt, as there's dategrep and dateconv already, albeit not in Fedora.

On the other hand, my project is older and more widely spread, so I could just go for the more narrative date prefix.

I feel like there should be a poll.  Even if it's just between the maintainers of openSuSE, Debian and Fedora.

**Comment by rudimeier** [comment]
"dt"  prefix is not bad but somehow I don't like dttest.
"du" for DateUtils could be ok too.
"date" is still my favorite. This could even make these tools more famous because names like "datediff" sound really self-evident and interesting for people who don't know it yet.

Another possibility would be to move all the commands into subcommands of one generic binary. But I have no idea for a good name for this. "dateutil", "dut", "dateng" ... don't know.

**Comment by mattdm** [comment]
For Fedora, "date-" is my preference. As @rudimeier says, it helps make the use self-evident.

I'd definitely prefer to _not_ go with a really long prefix like dateutils- for everything. 

But consistency with other distros is important, so I'll be happy to go along with consensus if people prefer something else.

**Comment by matthewfischer** [comment]
Debian and Ubuntu is already using dateutils as a prefix to solve the
namespace issue. It sounds like thats not the preference but it is the
prior art.

**Comment by mattdm** [comment]
So, like, `dateutils-dgrep`? I think that's more of a way to namespace, with the command "really" still bearing its upstream name; if we had a less clash-prone upstream name maybe that wouldn't be necessary. I hope. :)

**Comment by matthewfischer** [comment]
Yes, dateutils-dgrep (etc etc).

https://packages.debian.org/sid/amd64/dateutils/filelist

**Comment by mattdm** [comment]
Huh. I guess we _could_ do that, but it's close to making me retract my
idea of wanting to go with consensus. Too much typing. :)

-- 
Matthew Miller            mattdm@mattdm.org             <http://mattdm.org/>
Fedora Project Leader  mattdm@fedoraproject.org  <http://fedoraproject.org/>

**Comment by mattdm** [comment]
Thanks for doing this in the latest snapshots. For fedora, since the package was never there before, I'm going with `--without-old-links`. I notice that that still leaves the old _man pages_, though — do you want a separate issue filed for that?

**Comment by hroptatyr** [comment]
The man page issue ought to be fixed in 96a5495.

**Comment by hroptatyr** [comment]
The 0.3.3 release fully supports the new binary names.

**Comment by mattdm** [comment]
Thanks! And it is now [pending as an update for Fedora](https://admin.fedoraproject.org/updates/dateutils-0.3.3-3.fc22).
