### ISSUE TITLE
Incompatible with bison 2.3 on OS X

### ISSUE THREAD

**Issue by geezel** [hroptatyr/dateutils#35]
This suite doesn't compile on OS X 10.10.2 / XCode 6.1.1 that ships with a somewhat outdated version of bison:

.../dateutils/src/dexpr-parser.y:39.9-17: syntax error, unexpected string, expecting =

$ yacc -V
bison (GNU Bison) 2.3
Written by Robert Corbett and Richard Stallman.

Either fixing dexpr-parser.y or installing a more recent bison from MacPorts resolves that issue.

But I still get a couple of warnings for your extern inline declarations...

**Comment by hroptatyr** [comment]
Thanks for the bug report.

I tried to address the issue in 2e2502e.  Can you verify that this solves the problem?

If not, what do you mean by *fixing dexpr-parser.y*?

I'll address the extern inline issues separately.

**Comment by geezel** [comment]
Works. Thank you!
