### ISSUE TITLE
dconv --from-zone and --zone segmentation faults on Mac OSX Yosemite (10.10.3)

### ISSUE THREAD

**Issue by textarcana** [hroptatyr/dateutils#39]
Below is an example of the problem copy-pasted-from my terminal: 

    $ echo 2012-03-01T07:05:06 | dconv --from-zone=EDT
    2012-03-01T07:05:06

    $ echo 2012-03-01T07:05:06 | dconv --from-zone=UTC
    Segmentation fault: 11

    $ echo 2012-03-01T07:05:06 | dconv --from-zone America/New_York
    Segmentation fault: 11

I tried compiling with both the Mac OS default gcc and GNU gcc 4.6 from MacPorts but it doesn't seem to make a difference wrt this issue.

**Comment by hroptatyr** [comment]
What version does that relate to? And can you give me a backtrace somehow by any chance?

**Comment by textarcana** [comment]
I am using v0.3.3 — here is the crash report https://gist.github.com/textarcana/2e54c03b1a62c71b9562

Thanks for getting back so quickly!

**Comment by hroptatyr** [comment]
I've committed a series of patches just then (b3fcd93), addressing endian issues.
If that doesn't fix it, it's probably the way the tzinfo files are laid out.
So if you could email me one (say `/usr/share/zoneinfo/America/New_York`) in that case it'd be splendid.

**Comment by textarcana** [comment]
Unfortunately make fails for me on that revision. Here is the output from make: https://gist.github.com/textarcana/a8f115b32e5717ce79cc

**Comment by hroptatyr** [comment]
Ah that's good :) and just as I suspected, the endianness isn't detected correctly.
Or it's one of these Apple universal builds where they try to compile for both powerpc (big) and x86 (little) endianness.

Either way, looking at all the endianness-dependent code, I can probably fix the timezone stuff but I'm also using bitfields where knowing the endianness is a must, that code would stay broken.

Unfortunately, I haven't got a Mac to test things on (well, nor an idea what to test), so any attempt will be a blind shot.  I wonder how the homebrew people managed to do it?

**Comment by textarcana** [comment]
To be clear, the homebrew version DOES have the same bug. I believe they are on v2.5.  

Given what you've said, it's possible this particular feature hasn't ever worked on Mac!

I'm always happy to test any dateutils patches on Mac and report back to you, whether related to this particular bug or not :)

**Comment by hroptatyr** [comment]
That's great! :)
Would you mind sending me the config.log file (generated by running `./configure`)?

**Comment by textarcana** [comment]
I pulled current master branch and ran autoreconf -i and then configure. Here is the output from configure: https://gist.github.com/textarcana/cd98260ddecaa2b29222

**Comment by hroptatyr** [comment]
hehe, that's good to know already but there's a file `config.log` in the build directory produced by that configure run.

**Comment by textarcana** [comment]
oops! here it is https://gist.github.com/textarcana/fddef3549bb48bb77486

**Comment by hroptatyr** [comment]
Cool, thanks.  I've found what I was looking for (the headers needed for the ENDIAN macros).  Current master (94fb7ef) should contain a fix.

**Comment by hroptatyr** [comment]
Hey, have you had a chance to test the latest master yet?

**Comment by textarcana** [comment]
Thanks but I just tried and make failed.  Here is the config.log plus the output I got from make. Git master revision was d0e8ec8.

https://gist.github.com/textarcana/5e433e3169cdc8bcab6a

**Comment by hroptatyr** [comment]
Thanks. I've just pushed a gcc-specific hack (the macro `__ORDER_LITTLE_ENDIAN__`).  This is somewhat my last straw, if it doesn't work can you send me the output of

    cpp -dM /dev/null

**Comment by textarcana** [comment]
Sorry make still failed. Here is the output of cpp you requested: https://gist.github.com/textarcana/ce9d1cde2d6678b566f3

Thanks!

**Comment by hroptatyr** [comment]
Ah finally. I've noticed m logic was wrong because `__ORDER_LITTLE_ENDIAN__` and `__LITTLE_ENDIAN__` aren't the same value.  I pushed a patch to master (a36db3e) and hopefully it should now build at least.

**Comment by textarcana** [comment]
Yes! a36db3e fixes the original issue with time zones. No more seg faults!

Thank you so much!
