### ISSUE TITLE
Two-digit year dates with dconv produce errors in some cases

### ISSUE THREAD

**Issue by lienke** [hroptatyr/dateutils#41]
Hi. 
This script and output illustrates that year "97" produces "1997", but "67" produces "2067".  I'd like to see an option to set the difference or absolute value of the year date to handle the situation.

This is from an attempted solution on a forum.  I often demonstrate dateutils in solving user date issues on forums.

Thanks ... cheers, drl

```
#!/usr/bin/env bash

# @(#) s1l	Demonstrate date conversion, dateutils, dconv.

program=dconv
program=dateutils.dconv
# Utility functions: print-as-echo, print-line-with-visual-space, debug.
# export PATH="/usr/local/bin:/usr/bin:/bin"
LC_ALL=C ; LANG=C ; export LC_ALL LANG
pe() { for _i;do printf "%s" "$_i";done; printf "\n"; }
pl() { pe;pe "-----" ;pe "$*"; }
db() { ( printf " db, ";for _i;do printf "%s" "$_i";done;printf "\n" ) >&2 ; }
db() { : ; }
C=$HOME/bin/context && [ -f $C ] && $C $program

FILE=${1-data1}

pl " Input data file $FILE:"
cat $FILE

pl " Expected output:"
cat expected-output.txt

pl " Results:"
input='%d-%b-%y'
pe " Input format is \"$input\""
$program -i "$input" -f '%Y%m%d' -S < $FILE

exit 0
```

-----  output

```
$ ./s1

Environment: LC_ALL = C, LANG = C
(Versions displayed with local utility "version")
OS, ker|rel, machine: Linux, 3.16.0-4-amd64, x86_64
Distribution        : Debian 8.2 (jessie) 
bash GNU bash 4.3.30
dateutils.dconv dconv 0.3.1

-----
 Input data file data1:
Col1|col2|col3|col4|col5|col6-------col26
1|2|3|10-Nov-67|10-Nov-97|4|5-------100
1|2|3|11-Feb-01|01-Dec-15|4|5-------2000

-----
 Expected output:
Col1|col2|col3|col4|col5|col6-------col26
1|2|3|19671110|19971010|4|5-------100
1|2|3|20010211|20151201|4|5-------2000


-----
 Results:
 Input format is "%d-%b-%y"
Col1|col2|col3|col4|col5|col6-------col26
1|2|3|20671110|19971110|4|5-------100
1|2|3|20010211|20151201|4|5-------2000
```

**Comment by hroptatyr** [comment]
There is.  See `b|--base=DT', single digit or double digit years will be based around this value.

For instance (+/- 50 years):

    $ dateconv -b 2000-01-01 -i '%y-%m-%d' "57-01-01"
    =>
      1957-01-01

whereas

    $ dateconv -b 2000-01-01 -i '%y-%m-%d' "47-01-01"
    =>
      2047-01-01

And for single digit years (+10 years/-0 years) commonly used in the financial world:

    $ dconv -b 2000-01-01 -i '%_b%_y' F7
    =>
      2007-01-00
    $ dconv -b 2016-01-14 -i '%_b%_y' F7
    =>
      2017-01-00

**Comment by hroptatyr** [comment]
What *doesn't* work is to have this base date on a "per-line" basis.
Like birthday tables, they start with 07, 08, etc. standing for 1907, 1908
and throughout the file there's a wrap around 99 (being 1999) and then 00 again, this time standing for the year 2000.

While that would be amazing to have, it's very hard to phrase that in options.  A scripting language can be more expressive in this regard.

**Comment by lienke** [comment]
Hi, Sebastian.

Thanks.  That was not in the Debian 8 man page, and:

$ dateutils.dconv -b 2000-01-01 -i '%y-%m-%d' "57-01-01"
dconv: invalid option -b

Not your fault if Debian is behind.  I can either wait for Debian to 
catch up, or compile from source (as I have done at least once before).

Do you or I mark the issue as solved (or use of old version)?

Thanks for the speedy reply (as well as your time in doing the code) 
... cheers, drl

On Jan 14 2016 09:13 am, Sebastian Freundt wrote:

> There is. See `b|--base=DT', single digit or double digit years will 
> be
> based around this value.
> 
> For instance (+/- 50 years):
> 
> $ dateconv -b 2000-01-01 -i '%y-%m-%d' "57-01-01"
> =>
> 1957-01-01
> 
> whereas
> 
> $ dateconv -b 2000-01-01 -i '%y-%m-%d' "47-01-01"
> =>
> 2047-01-01
> 
> And for single digit years (+10 years/-0 years) commonly used in the
> financial world:
> 
> $ dconv -b 2000-01-01 -i '%_b%_y' F7
> =>
> 2007-01-00
> $ dconv -b 2016-01-14 -i '%_b%_y' F7
> =>
> 2017-01-00
> 
> --
> Reply to this email directly or view it on GitHub [1].


Links:
------
[1] 
https://github.com/hroptatyr/dateutils/issues/41#issuecomment-171668695

**Comment by hroptatyr** [comment]
Ok, sorry, should have mentioned that this feature was added in 0.3.3

I'll mark the issue as closed.  Thanks for the report anyway.

**Comment by lienke** [comment]
Hi.

Yes, I agree.  Data collections don't always easily fit into our codes, 
and some things are just too difficult or time-consuming to handle.  If 
I can deal with 90% of cases, then I feel pretty good, and I consider 
the rest "pathological".  I'll give up at that point, or wait until the 
coding muse shows me a clever solution.

cheers, drl

Jan 14 2016 09:17 am, Sebastian Freundt wrote:

> What _doesn't_ work is to have this base date on a "per-line" basis.
> Like birthday tables, they start with 07, 08, etc. standing for 1907,
> 1908
> and throughout the file there's a wrap around 99 (being 1999) and then
> 00 again, this time standing for the year 2000.
> 
> While that would be amazing to have, it's very hard to phrase that in
> options. A scripting language can be more expressive in this regard.
> 
> --
> Reply to this email directly or view it on GitHub [1].


Links:
------
[1] 
https://github.com/hroptatyr/dateutils/issues/41#issuecomment-171669681
