### ISSUE TITLE
\0 not supported in sed mod

### ISSUE THREAD

**Issue by heehoo59** [hroptatyr/dateutils#42]

**Comment by hroptatyr** [comment]
Thanks for the report.
What's the command line you were trying?

**Comment by heehoo59** [comment]
Dadd +4mo -S and my data contains one ^@ per line

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Thu, Jan 28, 2016 at 11:19 PM -0800, "Sebastian Freundt" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the report.
What's the command line you were trying?

-

**Comment by hroptatyr** [comment]
Hm, I've just tried

    $ dateadd +4mo -S <<EOF | cat -A
    2015-01-04^@a
    2015-02-02^@b
    EOF

with (^@) being a literal \0 and output is:

    2015-05-04^@a$
    2015-06-02^@b$

as expected.  What version are you using?  And, in case you compiled it yourself, what system/architecture?

**Comment by heehoo59** [comment]
All the dates after the ^@ are not changed.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Fri, Jan 29, 2016 at 4:45 AM -0800, "Sebastian Freundt" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hm, I've just tried

$ dateadd +4mo -S <<EOF | cat -A
2015-01-04^@a
2015-02-02^@b
EOF


with (^@) being a literal \0 and output is:

2015-05-04^@a$
2015-06-02^@b$


as expected. What version are you using? And, in case you compiled it yourself, what system/architecture?

-

**Comment by hroptatyr** [comment]
Well spotted, thanks.

A fix is in latest master (5bd20feb)

**Comment by hroptatyr** [comment]
This issue can (possibly) be worked around even with an unpatched dateutils:

    $ cat file | tr '\0' '\1' | dateadd +4mo -S | tr '\1' '\0'

in words: replace ASCII NUL character with ASCII SOH (`\1` or `^A`), pipe that stream
to the dateadd binary and substitute the SOH in the output stream by NUL again.

Basically any "unused" character can be a substitute, `\1` is just the next character in the
ASCII table and, being in the control character set, should be relatively rare in text files.
