### ISSUE TITLE
Installed from Ubuntu repository but datediff command not found

### ISSUE THREAD

**Issue by GrouchyGaijin** [hroptatyr/dateutils#43]
I installed dateutils with
`sudo apt-get install dateutils`

The package is listed as installed yet when I run

`datediff 2001-02-08 2001-03-02`

I get an error that the command datediff is not found.
I tried: `ddatediff 2001-02-08 2001-03-02` and get the same error.

How do I run dateutil commands?

**Comment by GrouchyGaijin** [comment]
Nevermind it worked when I used the full path.

`/usr/bin/dateutils.ddiff`

**Comment by hroptatyr** [comment]
Yes, only the newer Ubuntus get the unified names (`datediff`, `dateadd`, etc.).
