### ISSUE TITLE
dateround does nothing with `%s` input

### ISSUE THREAD

**Issue by chrisberkhout** [hroptatyr/dateutils#47]
This works:

    $ echo '2016-01-01 12:12:12' | dateround -i '%F %T' /15s
    2016-01-01T12:12:15

This doesn't:

    $ echo '2016-01-01 12:12:12' | strptime -i '%F %T' -f '%s' | dateround -i '%s' /15s
    2016-01-01T12:12:12

**Comment by hroptatyr** [comment]
Hi Chris,
thanks for reporting this.  A case of missing implementation; it should be fixed in 17a7a22.

**Comment by chrisberkhout** [comment]
Thanks for the quick fixes Sebastian!
