### ISSUE TITLE
segfault on missing input format

### ISSUE THREAD

**Issue by chrisberkhout** [hroptatyr/dateutils#48]
Example:

    $ echo 1900-01-01 | strptime -i '%F'
    1900-01-01

    $ echo 1900-01-01 | strptime -i 'foo'
    strptime: cannot make sense of `1900-01-01' using the given input formats

    $ echo 1900-01-01 | strptime -i
    Segmentation fault (core dumped)

Not sure if this one is intended...

    $ echo 1900-01-01 | strptime -i ''
    1900-01-00

**Comment by hroptatyr** [comment]
Hi again Chris,
thanks for reporting this.  A fix is in 380f951.
