### ISSUE TITLE
No format spec for non-zero padded day of month

### ISSUE THREAD

**Issue by abone28** [hroptatyr/dateutils#52]
Some logs contain non-zero padded dates (something like Oct  1 12:05:00).

As of dateutils version 0.4 there is no format spec for day of month that support non-zero padded dates. Available %d expect zero-padded date with two digits. So dconv is unable to convert such logs

Test case:

Properly handling 2 digits day of month

dconv --input-format "%b %d %H:%M:%S" --format "%F %T" "Oct 10 12:05:00"
2016-10-10 12:05:00

Error on white space padded sindle digit day of month

dconv --input-format "%b %d %H:%M:%S" --format "%F %T" "Oct  1 12:05:00"
dconv: cannot make sense of `Oct  1 12:05:00' using the given input formats

**Comment by hroptatyr** [comment]
Should be fixed in 1a9c643

Let me know what you think, and thanks for the report.

**Comment by abone28** [comment]
Fix works for me. I'm closing the issue now. Thank you.
