### ISSUE TITLE
dateadd ignoring day information

### ISSUE THREAD

**Issue by ankit7540** [hroptatyr/dateutils#53]
This is a very useful project. Thanks.
This problem is about how dadd responds to day information.

`dateutils.dadd 00:00:00:00 1d4h5m4s`
gives output as
`04:05:04`

The information about 1 day is ignored altogether. Any solution.

**Comment by hroptatyr** [comment]
`dadd` is for adding time periods (I call them duration in the docs) to dates.  What you want is adding durations to durations and there is no way and no tool in dateutils to do that.

For such simple cases you could always use `awk`, though parsing the summand and duration strings would be tricky.

If you want a dirty hack, just use a date as first argument and cut it off in the output again, like so:

    $ dateutils.dadd -i '%F:%T' 1700-01-00:00:00:00 +1d4h5m4s | cut -d- -f3-
    01T04:05:04

or to comply with your format:

    $ dateutils.dadd -i '%F:%T' -f '%F:%T' 1700-01-00:00:00:00 +1d4h5m4s | cut -d- -f3-
    01:04:05:04

**Comment by ankit7540** [comment]
Thanks. I managed to get a workaround using a fake date as starting point and using datediff. 

Your reply  is also nice. :-)
