### ISSUE TITLE
Feature Request: Support Months and Days Without Zero Padding

### ISSUE THREAD

**Issue by ode79** [hroptatyr/dateutils#55]
Using `date` you can add a hyphen after `%m` or `%d` to print the month or day without zero padding.

It would be useful to me if you could add this feature to dateutils (I am using dseq).

Thanks for the great project.

**Comment by hroptatyr** [comment]
Good idea, I've been thinking about this for a while already but never came up with a good modifier.
Seeing as the (GNU) date guys support it saves me some thinking.

My proposal is in: a87216a9.  Documentation hasn't been updated yet.

**Comment by ode79** [comment]
I've checked out the git version and see you have already committed the feature to master.

I've tested on my end and it looks good.

Thanks for the quick work!
