### ISSUE TITLE
Dateutils does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by gusbemacbe** [hroptatyr/dateutils#57]
Hello,

I typed `sudo apt-get install dateutils` and after I typed `dateutils` or `datediff...` via terminal and the terminal said the command not found.

**Comment by paperdigits** [comment]
From memory, it is something like dadd and ddiff on Debian/Ubuntu.

**Comment by LightningStalker** [comment]
Try dateutils-ddiff

Sent from my iPad

On Mar 14, 2017, at 2:54 PM, Mica <notifications@github.com<mailto:notifications@github.com>> wrote:

From memory, it is something like dadd and ddiff on Debian/Ubuntu.

**Comment by hroptatyr** [comment]
$ head -n2 /etc/os-release
    NAME="Ubuntu"
    VERSION="16.04.1 LTS (Xenial Xerus)"

By default you get a dateutils-0.3.1 on Debian and hence Ubuntu, the binaries have their old names with `dateutils.` prefixed:

    $ dateutils.dconv -V
    dconv 0.3.1

**Comment by gusbemacbe** [comment]
@paperdigits and @LightningStalker they didn't work either.

@hroptatyr 

It is the same thing, here are the results:

```
gusbemacbe@gustavo-linux:~$ head -n2 /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
gusbemacbe@gustavo-linux:~$ dateutils.dconv -V
dconv 0.3.1
gusbemacbe@gustavo-linux:~$ 
```

**Comment by paperdigits** [comment]
@gusbemacbe I'm on Debian Stable and I see:

```
pd@box:~$ dateutils.
dateutils.dadd      dateutils.ddiff     dateutils.dround    dateutils.dsort     dateutils.dzone
dateutils.dconv     dateutils.dgrep     dateutils.dseq      dateutils.dtest     dateutils.strptime
pd@box:~$ dateutils.dadd today +5d
2017-03-21
```

**Comment by j450h1** [comment]
Anyway to change the name from ```dateutils.dseq``` to ```dateseq``` so I can use the same code on Mac without an if statement?

**Comment by j450h1** [comment]
I ended up creating an alias as such: ```alias dateseq='dateutils.dseq'``` and also followed these steps: https://askubuntu.com/questions/17536/how-do-i-create-a-permanent-bash-alias

**Comment by hroptatyr** [comment]
@j450h1 Hi Jas,
you're talking about the ubuntu package here, right?  Sorry, this is out of my hands, you should be talking to the packagers as they decided to use prefixed binary names.  (It was to overcome a name clash with `dgrep` which is a debian internal tool, IIRC)

**Comment by j450h1** [comment]
@hroptatyr Yes, Ubuntu. Understood. I think my alias workaround should be sufficient. Thanks!

**Comment by adriel** [comment]
Loosely related, for those on **Mac**, you can install it with `brew install dateutils`
