### ISSUE TITLE
Duration between two times in different timezones

### ISSUE THREAD

**Issue by halloleo** [hroptatyr/dateutils#58]
I try to calculate the duration between two times in different time zones, but `datediff` does not seem to accept `--from-zone` for each time. Any other way to do this?

**Comment by hroptatyr** [comment]
I know it's a lot to type for just two dates, but using in-place `dateconv` to convert the times to UTC should work:

    $ datediff `dateconv --from-zone Europe/Moscow 2017-03-28T03:32:00` `dateconv --from-zone America/Chicago 2017-03-28T03:32:00`
    28800s
    $

Unless you have the offsets already, they can be added in ISO 8601 style:

    $ datediff 2017-03-28T03:32:00+03:00 2017-03-28T03:32:00-05:00
    28800s
    $

You can find the current offsets (or offsets in bulk) using `datezone`:

    $ datezone Europe/Moscow America/Chicago 2017-02-22T20:00:00 2017-03-28T01:00:00
    2017-02-22T23:00:00+03:00	Europe/Moscow
    2017-02-22T14:00:00-06:00	America/Chicago
    2017-03-28T04:00:00+03:00	Europe/Moscow
    2017-03-27T20:00:00-05:00	America/Chicago
    $

Iterate over zones, then times, i.e. the outer product of zone arguments and times arguments, here you obviously just need the first and last line (the diagonal if written as matrix).

**Comment by halloleo** [comment]
Yep, the in-place conversion does the job. Thanks!
