### ISSUE TITLE
Signed release tarballs

### ISSUE THREAD

**Issue by AladW** [hroptatyr/dateutils#59]
Since the commits are already verified, it would be a small step to also sign the release tarballs for distribution packaging.

**Comment by hroptatyr** [comment]
Thanks for the suggestion.  As I'm not a packager I have no expertise in this area.  Would it be enough to `gpg -ba TARBALL` and upload the `.asc` file?

**Comment by AladW** [comment]
I think that's the gist of it. This article gives an overview of the steps involved:

https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by hroptatyr** [comment]
Ok, I've signed the tarballs (because I think this aids longevity if me, you or
anyone in the future needs to recompress them) and put the .asc files in the
releases section.

**Comment by AladW** [comment]
Thank you very much. :+1:
