### ISSUE TITLE
dgrep time range expression

### ISSUE THREAD

**Issue by etopylight** [hroptatyr/dateutils#68]
Hi, thanks as always for maintaining such a wonderful toolkit.

I'm trying to use `dgrep` with `&&` to do a time range selection, however my command below returns nothing

    dgrep '>=2017-12-19 12:00:00 && <=2017-12-19 23:00:00' < input.txt

when given a input file `input.txt` like

    2017-12-18 12:00:00
    2017-12-19 03:45:50
    2017-12-19 19:14:05
    2017-12-19 22:16:29
    2017-12-20 13:00:00

Is there anything wrong with my expression syntax?

My current `dateutils` version

    $ dgrep --version
    dategrep 0.4.2.git5.5d4423e

**Comment by hroptatyr** [comment]
Hiya,

thanks.  Yes, there is a problem, the expression parser is extremely fussy, you need to omit the whitespace around `&&`, i.e.:

    $ dgrep '>=2017-12-19 12:00:00&&<=2017-12-19 23:00:00' <<EOF                                                                                2017-12-21T11:21:53
    2017-12-18 12:00:00
    2017-12-19 03:45:50
    2017-12-19 19:14:05
    2017-12-19 22:16:29
    2017-12-20 13:00:00
    EOF                                                                       
    =>
      2017-12-19 19:14:05
      2017-12-19 22:16:29

I guess I should review the parser.

**Comment by etopylight** [comment]
Hey nice, worked like a charm!

Yes, it would be great if the parser is able to allow white spaces between operators maybe in the future? Since I think it's quite instinctive especially for bash users to add spaces between logical operators and so it might also be hard for them to figure it out. :smile:

**Comment by hroptatyr** [comment]
Yes, definitely on my todo list now.  I must admit I, too, fall for this "peculiarity" quite regularly.
