### ISSUE TITLE
Datediff outputting 4 weeks & 5 days instead of 1 months & 2 days when

### ISSUE THREAD

**Issue by scotty49** [hroptatyr/dateutils#70]
Seems to be a problem when the output format is set to include months, weeks & days. For example, calculating the difference between New Year's Day & the 3rd of February (33 days or 1 month & 2 days)

```
datediff 2018-01-01T17:20:00 2018-02-03T18:20:00 -f "%m months, %w weeks & %d days" 

0 months, 4 weeks & 5 days
```
When the weeks output field is removed, I get the correct result:
```
datediff 2018-01-01T17:20:00 2018-02-03T18:20:00 -f "%m months, %d days"       
    
1 months, 2 days
```

**Comment by hroptatyr** [comment]
Hi scotty49,
thanks for the report.  Well spotted!

The current master (9aa7778d) contains a fix.

**Comment by scotty49** [comment]
I just installed the latest snapshot & it seems to be working fine now. Thank-you for such a quick response hroptatyr - it is much appreciated. Cheers :)
