### ISSUE TITLE
dateutils.dconv might have a bug with converting non-24 hr times

### ISSUE THREAD

**Issue by kihiukiragu** [hroptatyr/dateutils#93]
The following:
dateutils.dconv -i '%d-%b-%y %I.%M.%S.%N %p' '26-JAN-19 12.02.23.823355000 AM’

Returns ‘2019-01-26T12:02:23’ but should return ‘2019-01-26T00:02:23’

**Comment by hroptatyr** [comment]
Hi kihiukiragu,
thanks for the report.  However, in the current release (0.4.5) this very example seems to report the correct value:

    $ dateconv -i '%d-%b-%y %I.%M.%S.%N %p' '26-JAN-19 12.02.23.823355000 AM'                                            
    2019-01-26T00:02:23
