### ISSUE TITLE
No rule to make target 'dconv.h2m', needed by 'all'.  Stop.

### ISSUE THREAD

**Issue by Earnestly** [hroptatyr/dateutils#95]
* linux 4.20.5
* gcc 8.2.1
* glibc 2.29

Attempting to build the [latest](https://github.com/hroptatyr/dateutils/commit/9b5cd144f300d0030c5fb4b762e55c4815378ce8) commit results in a great deal of warnings and ultimately an error as per the title.

Here's a selection of unique warnings as they appear:

```
yuck-scmver.c:104:1: warning: ignoring attribute 'pure' because it conflicts with attribute 'const' [-Wattributes]
yuck.c:1336:6: warning: variable 'outfd' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
/usr/include/features.h:185:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
yuck.c:982:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
dadd.c:277:35: warning: passing argument 2 of 'dt_io_strpdt' from incompatible pointer type [-Wincompatible-pointer-types]
dround.c:265:15: warning: 'on' may be used uninitialized in this function [-Wmaybe-uninitialized]
dt-core-strpf.c:137:20: warning: missing braces around initializer [-Wmissing-braces]
tzmap.c:664:17: warning: missing initializer for field 'off' of 'struct tzmap_s' [-Wmissing-field-initializers]
fmt-special.gperf:109:1: warning: no previous prototype for '__fmt_special' [-Wmissing-prototypes]
```

The final error is:

```
Making all in info
make[1]: Entering directory '/home/earnest/build/staging/dateutils-git/src/dateutils/info'
make[1]: *** No rule to make target 'dconv.h2m', needed by 'all'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  GENTH2M  format
  GENTH2M  units
  GENTH2M  format-ddiff
make[1]: Leaving directory '/home/earnest/build/staging/dateutils-git/src/dateutils/info'
make: *** [Makefile;491: all-recursive] Error 1
```

Building with:

```sh
export CPPFLAGS=-D_FORTIFY_SOURCE=2
export CFLAGS='-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -g -fvar-tracking-assignments'
export LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
export MAKEFLAGS=-j4

cd dateutils
autoreconf -fi
./configure --prefix=/usr --with-old-links=no
make
```

Here is the full build log: https://ptpb.pw/FcI6

**Comment by hroptatyr** [comment]
Hi Earnest,
thanks for the report.  It appears that `make` cannot find the `dconv.yuck` file in the `src/` directory from within the `info/` directory during the build.  Or `make` doesn't understand the old-style `.x.y` rules.

Check the `Makefile.in` (or the final `Makefile`), there should be a `.yuck.h2m` rule in there, and if so then it simply cannot find the `dconv.yuck` files.

**Comment by Earnestly** [comment]
There is no `.yuck.h2m` rule in the top-level `Makefile`.  Is `yuck` some new of dependency?  Here's is the generated `Makefile` if interested: https://ptpb.pw/YJtp

I do get the following from `./configure`:

```
checking for yuck... no
```

But as it doesn't error out I assume it's optional.

**Comment by hroptatyr** [comment]
Ah, good catch.  It was an autoconf hiccup (included `AX_CHECK_YUCK` macro had different semantics due to an update).

Fix should be in 2062b0cc.

**Comment by Earnestly** [comment]
Hm, nothing seems to have changed.  I did confirm that the 2062b0cc1c35fe41378ea3e16514ccf441875b70 commit is present and the build is clean (re-cloned).

I still get roughly the same quantity of warnings about fallthrough, pure, etc.  And the error is still the same:

```
    cd dateutils
    autoreconf -fi
    ./configure --prefix=/usr --with-old-links=no
    make

...

    make[1]: Entering directory '/home/earnest/build/staging/dateutils-git/src/dateutils/info'
    make[1]: *** No rule to make target 'dconv.h2m', needed by 'all'.  Stop.
      GENTH2M  format
    make[1]: *** Waiting for unfinished jobs....
      GENTH2M  format-ddiff
      GENTH2M  units
    make[1]: Leaving directory '/home/earnest/build/staging/dateutils-git/src/dateutils/info'
    make: *** [Makefile;491: all-recursive] Error 1
```

**Comment by hroptatyr** [comment]
I fixed all relevant warnings in 73789da85, obviously there's nothing I can do about the fallthrough warnings because that is deliberate.

About the yuck rule, I suppose it must be some automake 1.16a thing.  I'm using 1.14 and the rule gets transferred to the Makefile.in and Makefile correctly.  I can confirm that I get the same error as you if I comment out the `.yuck.h2m` rule in the Makefile manually.

**Comment by Earnestly** [comment]
I get the following in my [`info/Makefile.in`](https://ptpb.pw/p9ks):

```make
.yuck.h2m: $(dateutils_EXAMPLES)
	$(my_bld_h2m) ${SHELL} \
		$(srcdir)/genh2m.sh $(top_builddir)/src/$* \
		$($*_EXAMPLES) > $@ || rm -f -- $@
```

PS: Didn't you mean to use `struct foo bar = {0};` instead of `struct foo bar = {};`?

**Comment by hroptatyr** [comment]
Yes, the `.yuck.h2m` rule is supposed to pick up `dconv.yuck` in the `src/` directory and turn it into `dconv.h2m`.  The error from make could mean two things: Either a rule to create `dconv.h2m` is missing in the Makefile (which you said is not the case), or the rule's prerequisite could not be found, `dconv.yuck` in this case, in which case the implicit rule isn't used at all.  Annoyingly, both problems result in the same error message.

I don't understand what you mean by having a target rule.  The target of the rule is `dconv.h2m`.

The problem, as it appears now, must be that `dconv.yuck` cannot be found, i.e. VPATH resolution has failed.

PS: yes, I used to use struct foo bar = {0} for compatibility with C89, but C99's compound literals and struct initialisers now guarantee any unmentioned field to be initialised to 0 (or equivalent).  Historically, gcc at one point demanded at least one field in the initialiser, to see whether it's a named initialisation (`= {.bar = 0}`) or a sequential one (`= {0,1,2}`).  I think by now, and with `-std=c99`, they downgraded that to a warning, and silenced the whole thing with `-std=c11`.

PPS: Yes I know, and every fallthrough case used to be marked (with lint's `/*@fallthrough@*/` syntax) but these days every static code checking tool requires their own syntax, or worse their own set of command line options to disable the warning.  I'm only using icc these days for its overall sanity regarding warnings and remarks.

**Comment by Earnestly** [comment]
I mean that `dconv.h2m` doesn't have a rule with which to build it even though it is used as a prerequisite of `dconv.man`.  Which is pretty much what the error message is indicating.

There does seem to be a `src/dconv.yuck` so it may be as you say.  That said the `info/Makefile` is generated with no `YUCK = ` value even though I've used `--with-included-yuck=yes` explicitly.

I've tried providing the path to the bin via `make YUCK=build-aux/yuck` as well without much luck.  When attempting to issue `make clean` I also get the error

```
make[1]: Leaving directory '/home/earnest/build/staging/dateutils-git/src/dateutils/build-aux'
/bin/sh: line 3: yuck: command not found
Making clean in build-aux
```

I've also tried building yuck first, reconfiguring with `YUCK` provided explicitly but that also didn't help.  It seems like almost every `.h2m` target is broken in the same way, e.g. `make -k`:

```
make[1]: *** No rule to make target 'dconv.h2m', needed by 'all'.
make[1]: *** No rule to make target 'dseq.h2m', needed by 'all'.
make[1]: *** No rule to make target 'dadd.h2m', needed by 'all'.
make[1]: *** No rule to make target 'dtest.h2m', needed by 'all'.
make[1]: *** No rule to make target 'ddiff.h2m', needed by 'all'.
make[1]: *** No rule to make target 'dgrep.h2m', needed by 'all'.
make[1]: *** No rule to make target 'dround.h2m', needed by 'all'.
make[1]: *** No rule to make target 'dzone.h2m', needed by 'all'.
make[1]: *** No rule to make target 'dsort.h2m', needed by 'all'.
make[1]: *** No rule to make target 'strptime.h2m', needed by 'all'.
make[1]: *** No rule to make target 'strptime.texi', needed by 'all'.
make[1]: *** No rule to make target 'dadd.texi', needed by 'dateadd.texi'.
make[1]: *** No rule to make target 'dconv.texi', needed by 'dateconv.texi'.
make[1]: *** No rule to make target 'ddiff.texi', needed by 'datediff.texi'.
make[1]: *** No rule to make target 'dgrep.texi', needed by 'dategrep.texi'.
make[1]: *** No rule to make target 'dround.texi', needed by 'dateround.texi'.
make[1]: *** No rule to make target 'dseq.texi', needed by 'dateseq.texi'.
make[1]: *** No rule to make target 'dsort.texi', needed by 'datesort.texi'.
make[1]: *** No rule to make target 'dtest.texi', needed by 'datetest.texi'.
make[1]: *** No rule to make target 'dzone.texi', needed by 'datezone.texi'.
```

As for static initialisation, you absolutely do need to use `{0}` in C99 and C11 (I'm not sure about C89 as it's not very well specified).  The ability to not include an initialiser list is a feature of C++ or your compiler is providing an extension that allows it for C code (e.g. GNU C provides an extension that allows for empty initialiser lists).  Perhaps `icc` isn't quite so sane after all.  :P

**Comment by hroptatyr** [comment]
But `dconv.h2m` can be generated using the `.yuck.h2m` implicit rule.  It just needs a `dconv.yuck`.  Maybe linking those yuck files into the `info/` directory would help?

You're right about the initialisers given 6.7.8.1 (the syntax BNF) but I'm looking for `-std=gnu11` and/or `-intel-extensions` during configure'ing so that should be fine.  I'm sure I've used other GNU-extensions, anyway.

**Comment by hroptatyr** [comment]
I've pushed 8a2c58364 that fixes the empty initialiser list warnings.

**Comment by Earnestly** [comment]
Symlinking the `yuck` files from `src` to the `info` directory hasn't helped.

I've also manually run the command as best I understand to create the `.h2m` files with the command translated from the `Makefile` (using a relative path for `../src` instead of absolute):

```
for t in dconv dseq dadd dtest ddiff dgrep dround dzone dsort strptime; do
    sh genh2m.sh ../build-aux/yuck ../src/"$t".yuck > "$t".h2m
done
```

This appears to work, but then it follows with a bunch more errors with other files such as the `texi` ones which I assume I need to manually create as above.  Looking at the double-prefix rules everything seems fine, or as fine as autotools can be comprehended by me, so I'm a bit perplexed as to why this doesn't work.

```
make: *** No rule to make target 'strptime.texi', needed by 'all'.
make: *** No rule to make target 'dadd.texi', needed by 'dateadd.texi'.
make: *** No rule to make target 'dconv.texi', needed by 'dateconv.texi'.
make: *** No rule to make target 'ddiff.texi', needed by 'datediff.texi'.
make: *** No rule to make target 'dgrep.texi', needed by 'dategrep.texi'.
make: *** No rule to make target 'dround.texi', needed by 'dateround.texi'.
make: *** No rule to make target 'dseq.texi', needed by 'dateseq.texi'.
make: *** No rule to make target 'dsort.texi', needed by 'datesort.texi'.
make: *** No rule to make target 'dtest.texi', needed by 'datetest.texi'.
make: *** No rule to make target 'dzone.texi', needed by 'datezone.texi'.
  GEN      strptime.man
  GEN      dadd.manu
sed 's/dadd/dateadd/g; s/dconv/dateconv/g; s/ddiff/datediff/g; s/dgrep/dategrep/g; s/dround/dateround/g; s/dseq/dateseq/g; s/dsort/datesort/g; s/dtest/datetest/g; s/dzone/datezone/g' < dadd.manu > dateadd.manu
  GEN      dconv.man
sed 's/dadd/dateadd/g; s/dconv/dateconv/g; s/ddiff/datediff/g; s/dgrep/dategrep/g; s/dround/dateround/g; s/dseq/dateseq/g; s/dsort/datesort/g; s/dtest/datetest/g; s/dzone/datezone/g' < dconv.man > dateconv.man
  GEN      ddiff.mand
sed 's/dadd/dateadd/g; s/dconv/dateconv/g; s/ddiff/datediff/g; s/dgrep/dategrep/g; s/dround/dateround/g; s/dseq/dateseq/g; s/dsort/datesort/g; s/dtest/datetest/g; s/dzone/datezone/g' < ddiff.mand > datediff.mand
  GEN      dgrep.man
sed 's/dadd/dateadd/g; s/dconv/dateconv/g; s/ddiff/datediff/g; s/dgrep/dategrep/g; s/dround/dateround/g; s/dseq/dateseq/g; s/dsort/datesort/g; s/dtest/datetest/g; s/dzone/datezone/g' < dgrep.man > dategrep.man
  GEN      dround.manu
sed 's/dadd/dateadd/g; s/dconv/dateconv/g; s/ddiff/datediff/g; s/dgrep/dategrep/g; s/dround/dateround/g; s/dseq/dateseq/g; s/dsort/datesort/g; s/dtest/datetest/g; s/dzone/datezone/g' < dround.manu > dateround.manu
  GEN      dseq.manu
sed 's/dadd/dateadd/g; s/dconv/dateconv/g; s/ddiff/datediff/g; s/dgrep/dategrep/g; s/dround/dateround/g; s/dseq/dateseq/g; s/dsort/datesort/g; s/dtest/datetest/g; s/dzone/datezone/g' < dseq.manu > dateseq.manu
  GEN      dsort.man
sed 's/dadd/dateadd/g; s/dconv/dateconv/g; s/ddiff/datediff/g; s/dgrep/dategrep/g; s/dround/dateround/g; s/dseq/dateseq/g; s/dsort/datesort/g; s/dtest/datetest/g; s/dzone/datezone/g' < dsort.man > datesort.man
  GEN      dtest.man
sed 's/dadd/dateadd/g; s/dconv/dateconv/g; s/ddiff/datediff/g; s/dgrep/dategrep/g; s/dround/dateround/g; s/dseq/dateseq/g; s/dsort/datesort/g; s/dtest/datetest/g; s/dzone/datezone/g' < dtest.man > datetest.man
  GEN      dzone.man
sed 's/dadd/dateadd/g; s/dconv/dateconv/g; s/ddiff/datediff/g; s/dgrep/dategrep/g; s/dround/dateround/g; s/dseq/dateseq/g; s/dsort/datesort/g; s/dtest/datetest/g; s/dzone/datezone/g' < dzone.man > datezone.man
make: Target 'all' not remade because of errors.
```

**Comment by Earnestly** [comment]
I think I may have uncovered exactly why this doesn't work.  In a new gnu make commit suffix rules with dependencies will not generate pattern rules:

```
commit 67e6d81256486cbf160208c5b7ea164964c49dd4
Author: Paul Smith <psmith@gnu.org>
Date:   Sun Sep 9 15:30:07 2018 -0400

    [SV 40657] Don't create pattern rules for suffix rules with deps.

    * NEWS: Update with a backward-compatibility warning.
    * src/rule.c (convert_to_pattern): If a suffix rule has dependencies,
    do not create a pattern rule for it.  According to the manual suffix
    rules with prerequisites are treated as normal targets.
    * tests/scrips/features/suffixrules: Create some regression tests for
    .SUFFIXES and suffix rules.
```

Welp.

**Comment by hroptatyr** [comment]
Ah, thanks for digging this up!  I tried to work around it in 930fd1746.

**Comment by Earnestly** [comment]
Thanks, that fixes it; the build and tests now complete without much issue.  What a goose chase, but at least the next release of gmake is covered.

**Comment by Earnestly** [comment]
Hahaha http://git.savannah.gnu.org/cgit/make.git/commit/?id=3b5e47b2e2904884a9d853848be3348b7cdd4f8a
