### ISSUE TITLE
Some problem to use dateutils with xargs

### ISSUE THREAD

**Issue by aborruso** [hroptatyr/dateutils#96]
Hi,
I have this input file

```
28 dicembre 1896
12 marzo 1909
20 maggio 1914
20 maggio 1914
29 gennaio 1919
22 settembre 1919
27 ottobre 1919
29 febbraio 1920
16 maggio 1920
30 settembre 1920
```

If I run

    cat input | xargs -I _ dateconv --from-locale it_IT -i '%d %B %Y' -f '%a, %d %b %Y' '_'

I have these errors

```
dconv: cannot make sense of `28 dicembre 1896' using the given input formats
dconv: cannot make sense of `12 marzo 1909' using the given input formats
dconv: cannot make sense of `20 maggio 1914' using the given input formats
dconv: cannot make sense of `20 maggio 1914' using the given input formats
dconv: cannot make sense of `29 gennaio 1919' using the given input formats
dconv: cannot make sense of `22 settembre 1919' using the given input formats
dconv: cannot make sense of `27 ottobre 1919' using the given input formats
dconv: cannot make sense of `29 febbraio 1920' using the given input formats
dconv: cannot make sense of `16 maggio 1920' using the given input formats
dconv: cannot make sense of `30 settembre 1920' using the given input formats
```

But if I run `dateconv --from-locale it_IT -i '%d %B %Y' -f '%a, %d %b %Y' '28 dicembre 1896'` I have the right result.

What's wrong in my command?

Thank you

**Comment by hroptatyr** [comment]
Hi Andrea,

I think the problem is with the replacement character you chose, `--from-locale it_IT` contains an underscore and would be replaced with the input.

Did you know you can pass the file to `dateconv` directly?  All tools read from standard input if the date/time arguments are omitted:

    $ cat input | dateconv --from-locale it_IT -i '%d %B %Y'
    1896-12-28
    1909-03-12
    ...

**Comment by aborruso** [comment]
You are always very kind.

Thank you
